### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by mkayys** [n8gallagher/fotopx#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
- missing links to backend and frontend routes in bullet format

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

- formatting (please look at bluebird: https://github.com/appacademy/bluebird/wiki/mvp-list) the ordered list is bolded
- time estimate in days, Heroku and Production READMe will be 0.5 days

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- for associations, backtick the table name as well, ex. photos table, bullet point about `user_id` references `users` <--- table name also backticked
- same with follows table, last bullet point: index on `[:photo_id, :user_id], unique: true`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
= fpr the users, profile page is a GET request, not POST
- is there a page on 500px where you can see all the users that are signed up on 500px? If not, will not need the GET /api/users route
- for photos, DELETE HTTP verb, route has singular photo instead of photos
- for follows, would nest the follows route under photos because the current user would be creating the follow so we can just get the user id through that information but would still need to figure out what photo this follow is for
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- don't have to say `ProfileComponent`, can just say `Profile`

**Comment by n8gallagher** [comment]
I worked through all the comments here and referenced other design docs for formatting as well as added my frontend and backend routes. Thanks and let me know if there are more issues!

**Comment by mkayys** [comment]
Just made another pass through and reviewed frontend and backend routes. Please take a look at the updated comments on the issue. Thanks for making the changes!

**Comment by n8gallagher** [comment]
for follows, would nest the follows route under photos because the current user would be creating the follow so we can just get the user id through that information but would still need to figure out what photo this follow is for
^ I think the functionality of follows is for the current user to follow another user, so that's why i nested the route under user, my MVPs don't include the likes on photos functionality but i might want to add that as my first bonus MVP and try to complete it since it makes a lot of sense for a photo site.

**Comment by n8gallagher** [comment]
I updated MVPs to make 'Likes' a core MVP and 'Follows' my first bonus MVP. I added a likes table and edited the follows table. Please advise if I should make any additional changes. Thanks!

**Comment by mkayys** [comment]
Last thing: I would just remove "the page should be adequately styled." bullet from your MVP docs. Personally, the adjective, adequately, doesn't sound there was effort put into the styling. It's sort of like "good enough".
